// <auto-generated />
using System;
using BartenderApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BartenderApplication.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250828192451_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("BartenderApp.Models.Cocktail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cocktails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Tequila, lime, triple sec, salted rim",
                            IsAvailable = true,
                            Name = "Margarita",
                            Price = 9.50m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Bourbon, bitters, sugar, orange twist",
                            IsAvailable = true,
                            Name = "Old Fashioned",
                            Price = 11.00m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Rum, mint, lime, soda",
                            IsAvailable = true,
                            Name = "Mojito",
                            Price = 10.00m
                        });
                });

            modelBuilder.Entity("BartenderApp.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CocktailId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CocktailId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BartenderApp.Models.Order", b =>
                {
                    b.HasOne("BartenderApp.Models.Cocktail", "Cocktail")
                        .WithMany()
                        .HasForeignKey("CocktailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cocktail");
                });
#pragma warning restore 612, 618
        }
    }
}
